# -*- coding: utf-8 -*-
"""InternCircle_Titanic_EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDdqNC1ZfqWNLLshLAU8obvKqs1VbgOG
"""

# ============================================================
# INTERN CIRCLE - TITANIC EXPLORATORY DATA ANALYSIS (EDA)
# ============================================================

import pandas as pd
import seaborn as sns

print("================================================")
print("       TITANIC EXPLORATORY DATA ANALYSIS")
print("================================================")

# ------------------------------------------------------------
# 1. LOAD DATASET
# ------------------------------------------------------------

df = sns.load_dataset("titanic")

print("\n1. DATASET LOADED SUCCESSFULLY")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])


# ------------------------------------------------------------
# 2. FIRST 5 ROWS
# ------------------------------------------------------------

print("\n2. FIRST 5 ROWS")
display(df.head())


# ------------------------------------------------------------
# 3. LAST 5 ROWS
# ------------------------------------------------------------

print("\n3. LAST 5 ROWS")
display(df.tail())


# ------------------------------------------------------------
# 4. DATASET INFORMATION
# ------------------------------------------------------------

print("\n4. DATASET INFORMATION")
df.info()


# ------------------------------------------------------------
# 5. STATISTICAL SUMMARY
# ------------------------------------------------------------

print("\n5. STATISTICAL SUMMARY")
display(df.describe())


# ------------------------------------------------------------
# 6. COLUMN NAMES
# ------------------------------------------------------------

print("\n6. COLUMN NAMES")
print(df.columns.tolist())


# ------------------------------------------------------------
# 7. CHECK MISSING VALUES
# ------------------------------------------------------------

print("\n7. MISSING VALUES")
missing_values = df.isnull().sum()
print(missing_values)


# ------------------------------------------------------------
# 8. MISSING VALUE PERCENTAGE
# ------------------------------------------------------------

print("\n8. MISSING VALUE PERCENTAGE")

missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage.sort_values(ascending=False))


# ------------------------------------------------------------
# 9. CHECK DUPLICATES
# ------------------------------------------------------------

print("\n9. DUPLICATE RECORDS")

duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)


# ------------------------------------------------------------
# 10. CREATE CLEAN COPY
# ------------------------------------------------------------

data = df.copy()


# ------------------------------------------------------------
# 11. REMOVE DUPLICATE ROWS
# ------------------------------------------------------------

data = data.drop_duplicates()

print("\n10. DUPLICATES REMOVED")
print("Original rows:", len(df))
print("Rows after removing duplicates:", len(data))


# ------------------------------------------------------------
# 12. HANDLE MISSING AGE VALUES
# ------------------------------------------------------------

data["age"] = data["age"].fillna(data["age"].median())

print("\n11. MISSING AGE VALUES HANDLED")
print("Missing age values:", data["age"].isnull().sum())


# ------------------------------------------------------------
# 13. HANDLE MISSING EMBARKED VALUES
# ------------------------------------------------------------

data["embarked"] = data["embarked"].fillna(
    data["embarked"].mode()[0]
)

print("\n12. MISSING EMBARKED VALUES HANDLED")
print("Missing embarked values:", data["embarked"].isnull().sum())


# ------------------------------------------------------------
# 14. REMOVE DECK COLUMN
# ------------------------------------------------------------

data = data.drop(columns=["deck"])

print("\n13. DECK COLUMN REMOVED")
print("Remaining columns:", data.shape[1])


# ------------------------------------------------------------
# 15. CHECK CLEANED DATASET
# ------------------------------------------------------------

print("\n14. CLEANED DATASET")
print("Dataset shape:", data.shape)

display(data.head())


# ------------------------------------------------------------
# 16. SURVIVAL COUNTS
# ------------------------------------------------------------

print("\n15. SURVIVAL COUNTS")

survival_counts = data["survived"].value_counts()

print(survival_counts)

print("\n0 = Did not survive")
print("1 = Survived")


# ------------------------------------------------------------
# 17. SURVIVAL PERCENTAGE
# ------------------------------------------------------------

print("\n16. SURVIVAL PERCENTAGE")

survival_percentage = (
    data["survived"].value_counts(normalize=True) * 100
)

print(survival_percentage.round(2))


# ------------------------------------------------------------
# 18. PASSENGERS BY GENDER
# ------------------------------------------------------------

print("\n17. PASSENGERS BY GENDER")

gender_counts = data["sex"].value_counts()

print(gender_counts)


# ------------------------------------------------------------
# 19. SURVIVAL RATE BY GENDER
# ------------------------------------------------------------

print("\n18. SURVIVAL RATE BY GENDER")

gender_survival = (
    data.groupby("sex")["survived"].mean() * 100
)

print(gender_survival.round(2))


# ------------------------------------------------------------
# 20. SURVIVAL RATE BY PASSENGER CLASS
# ------------------------------------------------------------

print("\n19. SURVIVAL RATE BY PASSENGER CLASS")

class_survival = (
    data.groupby("class")["survived"].mean() * 100
)

print(class_survival.round(2))


# ------------------------------------------------------------
# 21. AVERAGE FARE BY CLASS
# ------------------------------------------------------------

print("\n20. AVERAGE FARE BY PASSENGER CLASS")

average_fare = data.groupby("class")["fare"].mean()

print(average_fare.round(2))


# ------------------------------------------------------------
# 22. MULTIPLE AGGREGATIONS
# ------------------------------------------------------------

print("\n21. PASSENGER CLASS ANALYSIS")

class_analysis = data.groupby("class").agg(
    passengers=("survived", "count"),
    survival_rate=("survived", "mean"),
    average_age=("age", "mean"),
    average_fare=("fare", "mean")
)

class_analysis["survival_rate"] = (
    class_analysis["survival_rate"] * 100
)

display(class_analysis.round(2))


# ------------------------------------------------------------
# 23. GENDER + CLASS ANALYSIS
# ------------------------------------------------------------

print("\n22. GENDER AND CLASS SURVIVAL ANALYSIS")

gender_class_analysis = data.groupby(
    ["class", "sex"]
)["survived"].agg(["count", "mean"])

gender_class_analysis["mean"] = (
    gender_class_analysis["mean"] * 100
)

display(gender_class_analysis.round(2))


# ------------------------------------------------------------
# 24. YOUNGEST AND OLDEST PASSENGER
# ------------------------------------------------------------

print("\n23. AGE ANALYSIS")

print("Youngest passenger age:", data["age"].min())
print("Oldest passenger age:", data["age"].max())


# ------------------------------------------------------------
# 25. AVERAGE AGE AND FARE
# ------------------------------------------------------------

print("\n24. OVERALL AVERAGES")

print(
    "Average passenger age:",
    round(data["age"].mean(), 2)
)

print(
    "Average ticket fare:",
    round(data["fare"].mean(), 2)
)


# ------------------------------------------------------------
# 26. FINAL EDA SUMMARY
# ------------------------------------------------------------

print("\n================================================")
print("             FINAL EDA SUMMARY")
print("================================================")

print("\nDataset shape:", data.shape)

print(
    "Overall survival rate:",
    round(data["survived"].mean() * 100, 2),
    "%"
)

print(
    "Average passenger age:",
    round(data["age"].mean(), 2)
)

print(
    "Average ticket fare:",
    round(data["fare"].mean(), 2)
)

print("\nSurvival rate by gender:")
print(
    (data.groupby("sex")["survived"].mean() * 100).round(2)
)

print("\nSurvival rate by passenger class:")
print(
    (data.groupby("class")["survived"].mean() * 100).round(2)
)

print("\n================================================")
print("       TITANIC EDA COMPLETED SUCCESSFULLY!")
print("================================================")